title: TOSSH Documentation
author: Gnann et al.
# email: sebastian.gnann@bristol.ac.uk
description: Toolbox for Streamflow Signatures in Hydrology # > # this means to ignore newlines until "show_excerpts:"
show_excerpts: true # set to true to show excerpts on the homepage
github_username: TOSSHtoolbox
url: https://TOSSHtoolbox.github.io/TOSSH/

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: TOSSHtoolbox/TOSSH
    # twitter: jekyllrb
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - p1_overview.md
 - p2_signatures.md
 - p3_examples.md
 - p4_contact.md

# Build settings
markdown: kramdown
kramdown:
    auto_ids: true
theme: minima
# theme: jekyll-theme-leap-day
# remote_theme: daviddarnes/alembi #"mmistakes/minimal-mistakes@4.19.3"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 #- jekyll-include-cache
 #- jekyll-remote-theme
 